version: "3.8"

networks:
  selenium:
    driver: bridge
    name: selenium

services:

  selenium-hub:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20201009
    networks:
      - selenium
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=3000
      - GRID_BROWSER_TIMEOUT=0

  chrome:
    image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20201009
    networks:
      - selenium
    ports:
      - "6900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=32

  firefox:
    image: selenium/node-firefox:4.0.0-alpha-7-prerelease-20201009
    networks:
      - selenium
    ports:
      - "6901:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=32