version: "3.8"
networks:
  selenium:
    driver: bridge
    name: selenium
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    networks:
      - selenium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=3000
      - GRID_BROWSER_TIMEOUT=0